In [1]:
import numpy as np

In [2]:
arr = np.array([2,4,5,2,4,5,2,4,3])
arr

array([2, 4, 5, 2, 4, 5, 2, 4, 3])

In [3]:
np.sort(arr)

array([2, 2, 2, 3, 4, 4, 4, 5, 5])

In [4]:
np.argsort(arr)

array([0, 3, 6, 8, 1, 4, 7, 2, 5])

In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [6]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [8]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [9]:
array_example.ndim

3

In [10]:
array_example.size

24

In [11]:
array_example.shape

(3, 2, 4)

In [12]:
arr.reshape(3,3)

array([[2, 4, 5],
       [2, 4, 5],
       [2, 4, 3]])