In [1]:
import numpy as np

In [2]:
data = np.array([1,2,3])

In [3]:
data[2]

np.int64(3)

In [4]:
data[0:2]

array([1, 2])

In [5]:
data[-2:]

array([2, 3])

In [6]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [7]:
print(a[a<5])

[1 2 3 4]


In [9]:
five_up = (a>=5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [11]:
a[(a>5) & (a%2==0)]

array([ 6,  8, 10, 12])

In [12]:
b = np.nonzero(a<5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))