In [1]:
import numpy as np

In [2]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data[0,1]

np.int64(2)

In [6]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [7]:
data[0:2,0]

array([1, 3])

In [9]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data



array([[1, 2],
       [5, 3],
       [4, 6]])

In [11]:
data.max(axis=1)

array([2, 5, 6])

In [12]:
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [13]:
ones = np.ones([1,1])

In [14]:
data + ones

array([[2., 3.],
       [6., 4.],
       [5., 7.]])

In [15]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [16]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [17]:
unique_values = np.unique(a)

In [18]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
occurence_counts = np.unique(a,return_counts=True)
occurence_counts

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))

In [20]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [21]:
unique_values = np.unique(a_2d)
unique_values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])