In [1]:
import numpy as np

In [2]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a1 = a[3:6]
a1

array([4, 5, 6])

In [6]:
b1 = np.array([[1,1],
             [2,2] ])
b2 = np.array([[3,3],
               [4,4]])

In [7]:
np.vstack((b1,b2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [8]:
np.hstack((b1,b2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [9]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [10]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [11]:
y = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [12]:
y1 = y[0,:]

In [13]:
y1

array([1, 2, 3, 4])

In [14]:
y1[0]=12

In [15]:
y1

array([12,  2,  3,  4])

In [16]:
y

array([[12,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
y2 = y.copy()

In [18]:
y2

array([[12,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
data = np.array([1,2])
ones = np.ones(2,dtype=int)
data + ones

array([2, 3])

In [23]:
arr = np.array([1,2,3,4])
arr.sum()

np.int64(10)