In [1]:
import numpy as np

In [2]:
np.zeros(2)

array([0., 0.])

In [4]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.empty(2)

array([0., 0.])

In [10]:
np.arange(4)


array([0, 1, 2, 3])

In [11]:
np.arange(2,12,3)

array([ 2,  5,  8, 11])

In [14]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
x = np.ones(2, dtype=np.int64)

In [16]:
x

array([1, 1])